baseURL = "https://rickbergfalk.github.io/"
languageCode = "en-us"
title = "Rick Bergfalk"
theme = "ananke"
publishDir = ".."
pygmentsCodeFences = true

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "My github pages"
  facebook = ""
  twitter = "https://twitter.com/rickbergfalk"
  instagram = ""
  youtube = ""
  github = "https://github.com/rickbergfalk"
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  featured_image = "/images/osman-rana-267042-min.jpg"
  recent_posts_number = 2